name: Deploy into VPS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository  # upload the repo into virtual machine 
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Deploy into VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd /var/www/bank-sampah

          # Pull update
          git pull origin main

          # Build assets
          npm install
          npm run build

          # Laravel preparation
          composer install --no-dev --optimize-autoloader
          # php artisan migrate --force
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear

          # Set permission
          chmod -R 755 storage
          chmod -R 755 bootstrap/cache
        EOF
